orbs:
  stackhawk: stackhawk/stackhawk@1.0.5

version: 2.1

workflows:
  scan-remote:
    jobs:
      - stackhawk/hawkscan-remote:
          configuration-files: stackhawk.yml
          host: 'https://zap.productplan.com'
